### ISSUE TITLE
[feature] 검색 페이지에서 input 컴포넌트에 데이터 내려주기

### ISSUE THREAD

**Issue by devmagrfs** [wanted-group-4/movie-info-site#12]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail: 검색 페이지에서 input 컴포넌트 연결하기 세팅하기

## TODO
- [x] 검색페이지 input 컴포넌트 디자인 틀 잡기
- [x] 검색페이지 input 컴포넌트에 props 내려주기 설정하기
- [x] onFocus, onBlur 를 통해서 포커스가 있을 때와 없을 때 css 변화주기 
- [x] onChange, onKeyPress 를 통해 검색이 가능하게 만들기

## Labels
Estimated time: E: `2h`
Group : `client`
