### ISSUE TITLE
[design] 상세페이지 변경디자인 적용

### ISSUE THREAD

**Issue by mrlee323** [wanted-group-4/movie-info-site#16]
## ISSUE
- Group: `client`
- Type: `css` 
- Detail: Modify Design

## TODO
- [x] mock data 변경으로 인한 디자인 수정
- [x] 상세페이지 디자인 수정 
- [x] 페이지에서 컴포넌트로 이동

## Labels
Estimated time: E: `2h`
Group : `client`
