### ISSUE TITLE
[feature] search 페이지에서 최근 검색어 기능 구현하기

### ISSUE THREAD

**Issue by devmagrfs** [wanted-group-4/movie-info-site#24]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail: 검색 페이지에서 검색어 input 클릭 시 최근 검색어 볼 수 있게 해주고, 검색 할 때마다 최근 검색어 리스트 추가시키기

## TODO
- [x] 검색을 할 때마다 localStorage에 저장하기
- [x] 최근 검색어가 없을 시 : input 클릭 시 최근 검색어가 없다고 보여주기
- [x] 최근 검색어가 있을 시 : 검색어를 localStorage에서 갖고와서 리스트로 보여주기

## Labels
Estimated time: E: `3h`
Group : `client`
