### ISSUE TITLE
[design] 상세페이지 반응형적용 

### ISSUE THREAD

**Issue by mrlee323** [wanted-group-4/movie-info-site#34]
## ISSUE
- Group: `client`
- Type: design
- Detail: add reposive css

## TODO
- [x] 상세페이지 반응형 적용
- [x] back button에 navigete 추가
- [x] json server 파일 경로 root로 이동

## Labels
Estimated time: E: `1h`
Group : `client`,
