### ISSUE TITLE
[refactor] 코드 통일화

### ISSUE THREAD

**Issue by Hotsumm** [wanted-group-4/movie-info-site#36]
## ISSUE
- Group: `client`
- Type:  `refactor`
- Detail: [refactor] 코드 통일화

## TODO
- [ ] 전체적인 코드 리팩토링 
- [ ] 통일되지 않은 코드 컨벤션에 맞게 통일화
- [ ] clean code 적용

## Labels
Estimated time: E: `3h`
Group : `client`
