### ISSUE TITLE
[feature] 상세페이지 비슷한영화 리스트 추가 

### ISSUE THREAD

**Issue by mrlee323** [wanted-group-4/movie-info-site#38]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail: add list of similar movies

## TODO
- [x] 상세페이지 비슷한 영화 리스트 추가
- [x] 비슷한 영화 랜덤 추출 함수 생성
- [x] 즐겨찾기 버튼 기능 추가
- [x] css refactoring

## Labels
Estimated time: E: `1.5h`
Group : `client`
