### ISSUE TITLE
[fix] import 디렉토리, 슬라이더 수정

### ISSUE THREAD

**Issue by greenish0902** [wanted-group-4/movie-info-site#50]
## ISSUE
- Group: `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete` ,`css` 등등 
- Detail: fix actions from client redux

## TODO
- [x] 슬라이더 좌우 이동 버튼 로직 수정
- [x] PostCard, PostRow 렌더링 최적화
- [x] 디렉토리 생성 및 import 경로 수정

## Labels
Estimated time: `1h`
Group : `client`
