### ISSUE TITLE
[feature] json-server 활용한 restful api 구현

### ISSUE THREAD

**Issue by JiehoonPark** [wanted-group-4/movie-info-site#8]
## ISSUE
- Group: `server`
- Type: `feature`
- Detail: `json-server 활용한 restful api 구현`

## TODO
- [ ] json-server 실행 스크립트 추가
- [ ] axios 설정 공통화
- [ ] 영화 데이터 fetching hook 
- [ ] 좋아요 데이터 patching hook

## Labels
Estimated time: E: `3h`
Group : `server`
