### ISSUE TITLE
[feature] json-server를 이용하여 REST API 구축하기

### ISSUE THREAD

**Issue by JiehoonPark** [wanted-group-4/movie-info-site#9]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail:  json-server를 이용하여 REST API 구축하기

## TODO
- [ ] json-server 실행 스크립트 & json파일 경로 설정 
- [ ] axios 설정 공통화
- [ ] 영화 데이터 가져오기
- [ ] 좋아요 기능 

## Labels
Estimated time: E: `3h`
Group : `client`
